init:
  - ps: |
        $ErrorActionPreference = "Stop"
        Invoke-WebRequest http://raw.github.com/krlmlr/r-appveyor/master/scripts/appveyor-tool.ps1 -OutFile "..\appveyor-tool.ps1"
        Import-Module '..\appveyor-tool.ps1'
  - cmd: echo "https://:@cida.usgs.gov" > C:\projects\.anonymous-git-credentials
  - cmd: git config --global credential.helper "store --file C:\projects\.anonymous-git-credentials"

install:
  - ps: Bootstrap

environment:
  NOT_CRAN: "true"

before_build:
  - cmd: git config --global credential.helper "store --file .anonymous-git-credentials"

build_script:
  - travis-tool.sh install_deps

test_script:
  - travis-tool.sh run_tests

on_failure:
  - git lfs logs last
  - travis-tool.sh dump_logs

artifacts:
  - path: '*.Rcheck\**\*.log'
    name: Logs

  - path: '*.Rcheck\**\*.out'
    name: Logs

  - path: '*.Rcheck\**\*.fail'
    name: Logs

  - path: '*.Rcheck\**\*.Rout'
    name: Logs

  - path: '\*_*.tar.gz'
    name: Bits

  - path: '\*_*.zip'
    name: Bits
